# 应用服务web访问端口
server:
  port: 8889


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: validate
entitymanager:
  packagesToScan: com.city.shophibernate.model
logging:
  level:
    com:
      city: debug